### ISSUE TITLE
Barking

### ISSUE THREAD

**Issue by colbystuart** [Ragnarok9401/intro_software_eng_jf1774#10]
Have a button available on the home screen where users can post a bark. Once the user clicks the button, they can then type out their post and hit post and then what they typed will be visible to everyone who is friends with them. Other users will be able to yip, howl, and give a treat to this post. This post will be able to be seen from the poster's profile and the homepage.

**Comment by j-neeley** [comment]
Related user story:
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%234-%E2%80%90-Posting-a-Bark

**Comment by colbystuart** [comment]
backend is done
