### ISSUE TITLE
Bark Interaction

### ISSUE THREAD

**Issue by Ragnarok9401** [Ragnarok9401/intro_software_eng_jf1774#11]
# Treating
Allow a user to click a Treat button that adds to the Bark's "Treat count." Clicking the button will also add the account to the "Treated" list for the Bark. If the same account clicks the Treat button a second time, it will remove the Treat from the Bark. This will also remove the account from the Bark's "Treated" list. Subsequent clicks on the Treat button will toggle whether the Bark is Treated by this account.

# Howling
Allow a user to click on a Howl button that adds the Bark to the user's Timeline as a Quoted Bark. Clicking this button will automatically copy over all contents of the original Bark as well as the original Bark poster's DawgTag to the new post under the account that requests the Howl. The "Howled" Bark can be Howled again by other accounts, but will keep the original account's name as the quoted account. A user may not press a Howl button on their own posts, and a user may not Howl another user's Howl if the post has already been Howled by the first user.

# Yipping
Allow a user to click on a Yip button on a post which brings up a text box. Users can write to this text box and add the Yip below the original Bark. This will also add to the original Bark's Yip count. Yips can also be edited by the Yip poster, which brings up a text box with all of the contents of the Yip present. If any changes are made, this will update the Yip on confirmation. Adding a new Yip and editing a current Yip can both be cancelled with no changes applied to the Bark's comments or to the Yip, if present.

**Comment by j-neeley** [comment]
Relevant User Stories:
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%235-%E2%80%90-Giving-Treats
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%236-%E2%80%90-Commenting-on-Barks-(Yipping)
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%2310-%E2%80%90-Howling
