### ISSUE TITLE
Create Account Page (FrontEnd)

### ISSUE THREAD

**Issue by AlonsoArreguin** [Ragnarok9401/intro_software_eng_jf1774#15]
Use HTML to develop and design create account page based on agreed Figma design page
Develop and Design Join the Pack button
Create Text Box for information needed to create an account for DawgHouse

Figma Design: https://www.figma.com/file/rwQBs8FEisUThTHrMTk93H/Untitled?type=design&node-id=36-220&mode=design&t=Re9qqiSwLDm8YRVi-0

**Comment by j-neeley** [comment]
Relevant User Story
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%239-%E2%80%90-Profile-Page

**Comment by j-neeley** [comment]
Relevant User Story
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%233-%E2%80%90-User-Account-Creation
