### ISSUE TITLE
Broken Treat Buttons

### ISSUE THREAD

**Issue by SyddWhit** [Ragnarok9401/intro_software_eng_jf1774#44]
Treat buttons wont turn maroon once clicked and users can remove another users treat.

**Comment by j-neeley** [comment]
This seems to only be an issue when giving treats to other users' posts.

**Comment by colbystuart** [comment]
repost buttons also need to turn maroon once reposted, and return grey if un-reposted

**Comment by colbystuart** [comment]
on friend view giving a treat redirects me to main timeline and doesn't show maroon on friend view. Everything seems to work fine on the timeline

**Comment by j-neeley** [comment]
This is only an issue on a friend's profile page. It works properly when liking posts on the main timeline and your own profile page

**Comment by j-neeley** [comment]
This has been fixed in the latest commit. Closing issue.
