### ISSUE TITLE
Creating Log in/ Log out page

### ISSUE THREAD

**Issue by SyddWhit** [Ragnarok9401/intro_software_eng_jf1774#7]
Create a user interface that involves a username and password field, a login and logout button, and a user friendly UI. Make sure it appeals to MSU students.

**Comment by j-neeley** [comment]
This is tied with Issue #3

**Comment by j-neeley** [comment]
Relevant User Story:
https://github.com/Ragnarok9401/intro_software_eng_jf1774/wiki/User-Story-%232-%E2%80%90-User-Login-Functionality
